Add support for OPOS6UL SoM

diff --git a/apf-config b/apf-config
--- a/apf-config
+++ b/apf-config
@@ -1,6 +1,6 @@
 #!/bin/sh
-# Part of apf-config https://github.com/artemysfr/raspi-config
-# Derived from raspi-config http://github.com/asb/raspi-config
+# This script is part of apf-config https://github.com/artemysfr/raspi-config
+# which is derived from raspi-config http://github.com/asb/raspi-config
 #
 # See LICENSE file for copyright and license details
 
@@ -34,8 +34,8 @@ calc_wt_size() {
 do_about() {
   whiptail --msgbox "\
 This tool provides a straight-forward way of doing initial
-configuration of the APF6 module, for the lazy ones that don't
-want to read Armadeus Wiki (http://www.armadeus.org).
+configuration of the APF6 & OPOS6UL SOM, for the lazy ones that
+don't want to read Armadeus Wiki (http://www.armadeus.org).
 
 Although it can be run at any time, some of the options may
 have difficulties if you have already customised your
@@ -47,22 +47,31 @@ It is heavily based on raspi-config.\
 
 do_expand_rootfs() {
   if ! [ -h /dev/root ]; then
-    whiptail --msgbox "I assume you're running in failsafe mode and will expand APF6 eMMC Boot and Rootfs partitions" 20 60 2
-    ROOT_PART=mmcblk2p2
+    if [ "$1" == "APF6" ]; then
+        whiptail --msgbox "I assume you're running in recovery mode and will expand APF6 eMMC Boot and Rootfs partitions" 20 60 2
+        MMC_DEV=mmcblk2
+        ROOT_PART=p2
+    fi
+    if [ "$1" == "OPOS6UL" ]; then
+        whiptail --msgbox "I assume you're running in recovery mode and will expand OPOS6UL eMMC Failsafe and Rootfs partitions" 20 60 2
+        MMC_DEV=mmcblk0
+        ROOT_PART=p2
+    fi
+    ROOT_DEV=$MMC_DEV$ROOT_PART
   else
-    ROOT_PART=$(readlink /dev/root)
+    ROOT_DEV=$(readlink /dev/root)
   fi
 
-  PART_NUM=${ROOT_PART#mmcblk}
-  if [ "$PART_NUM" = "$ROOT_PART" ]; then
+  PART_NUM=${ROOT_DEV#mmcblk[0-2]}
+  if [ "$PART_NUM" != "$ROOT_PART" ]; then
     whiptail --msgbox "/dev/root is not an eMMC/SD card. Don't know how to expand" 20 60 2
     return 0
   fi
 
-  resize2fs /dev/$ROOT_PART
-  if [ "$ROOT_PART" == mmcblk2p2 ]; then
-    # also resize Boot partition of eMMC
-    resize2fs /dev/mmcblk2p1
+  resize2fs /dev/$ROOT_DEV
+  if [ "$PART_NUM" == p2 ]; then
+    # also resize Boot or Failsafe partition of eMMC
+    resize2fs /dev/${MMC_DEV}p1
   fi
 
   RES="$?"
@@ -73,46 +82,52 @@ do_expand_rootfs() {
   return $RES
 }
 
+# $1: eMMC device name
 do_check_emmc() {
   if [ -h /dev/root ]; then
-    whiptail --msgbox "Can only be run in failsafe mode." 20 60 2
+    whiptail --msgbox "Can only be run in recovery mode." 20 60 2
     return 0
   fi
 
-  whiptail --yesno "This may alter the content of your APF6 eMMC !" 20 60 2 \
+  whiptail --yesno "This may alter the content of your eMMC !" 20 60 2 \
     --yes-button Ok --no-button Cancel
   RET=$?
   if [ "$RET" -eq 0 ]; then
-    e2fsck /dev/mmcblk2p1 &&
-    e2fsck /dev/mmcblk2p2 &&
+    e2fsck /dev/$1p1 &&
+    e2fsck /dev/$1p2 &&
     whiptail --msgbox "Your eMMC have been successfully checked !" 20 60 2
   fi
 }
 
+# $1: eMMC device name
 do_clear_emmc() {
   if [ -h /dev/root ]; then
-    whiptail --msgbox "Can only be run in failsafe mode." 20 60 2
+    whiptail --msgbox "Can only be run in recovery mode." 20 60 2
     return 0
   fi
 
-  whiptail --yesno "This will completly erase your APF6 eMMC and may take up to 15 mins !" 20 60 2 \
+  whiptail --yesno "This will completly erase your module's eMMC and may take up to 15 mins !" 20 60 2 \
     --yes-button Ok --no-button Cancel
   RET=$?
   if [ "$RET" -eq 0 ]; then
     # 7680000 should be 7733248 but seems to much
-    dd if=/dev/zero bs=512 count=7680000 | pv | dd of=/dev/mmcblk2 &&
+    dd if=/dev/zero bs=512 count=7680000 | pv | dd of=/dev/$1 &&
     whiptail --msgbox "Your eMMC have been successfully filled with zeroes !" 20 60 2
     RET=$?
   fi
   return $RET
 }
 
+# $1: board name
 do_format_emmc() {
-  whiptail --yesno "This will erase all the content of your APF6 eMMC !" 20 60 2 \
+  whiptail --yesno "This will erase all the content of your module's eMMC !" 20 60 2 \
     --yes-button Ok --no-button Cancel
   RET=$?
   if [ $RET -eq 0 ]; then
-    fdisk /dev/mmcblk2 << EOF
+
+    # APF6 (See http://www.armadeus.org/wiki/index.php?title=EMMC)
+    if [ "$1" == "APF6" ]; then
+      fdisk /dev/mmcblk2 << EOF
 o
 n
 p
@@ -126,14 +141,45 @@ p
 
 w
 EOF
-    # Force re-read of partition table
-    sleep 3 && hdparm -z /dev/mmcblk2
-    mkfs.ext4 -L "BOOT" -F /dev/mmcblk2p1 &&
-    mkfs.ext4 -L "ROOTFS" -F /dev/mmcblk2p2
-    RET=$?
-    if [ "$create_home" == "y" ]; then
-      mkfs.ext4 -L "HOME" -F /dev/mmcblk2p3
+      # Force re-read of partition table
+      sleep 3 && hdparm -z /dev/mmcblk2
+      mkfs.ext4 -L "BOOT" -F /dev/mmcblk2p1 &&
+      mkfs.ext4 -L "ROOTFS" -F /dev/mmcblk2p2
+      RET=$?
+      if [ "$create_home" == "y" ]; then
+        mkfs.ext4 -L "HOME" -F /dev/mmcblk2p3
+      fi
     fi
+
+    # OPOS6UL (See http://www.armadeus.org/wiki/index.php?title=EMMC_OPOS6UL)
+    if [ "$1" == "OPOS6UL" ]; then
+      fdisk /dev/mmcblk0 << EOF
+o
+n
+p
+1
+2048
++128M
+n
+p
+2
+
++2G
+n
+p
+3
+
+
+w
+EOF
+      # Force re-read of partition table
+      sleep 3 && hdparm -z /dev/mmcblk0
+      mkfs.ext4 -L "SAFE" -F /dev/mmcblk0p1 &&
+      mkfs.ext4 -L "ROOTFS" -F /dev/mmcblk0p2 &&
+      mkfs.ext4 -L "HOME" -F /dev/mmcblk0p3
+      RET=$?
+    fi
+
     if [ "$RET" -eq 0 ]; then
       whiptail --msgbox "Your eMMC have been successfully formatted !" 20 60 2
     else
@@ -212,10 +258,10 @@ do_overscan() {
 
 do_change_pass() {
   if ! [ -h /dev/root ]; then
-    whiptail --msgbox "Can't change password in failsafe mode !" 20 60 1
+    whiptail --msgbox "Can't change password in recovery mode !" 20 60 1
     return 0
   fi
-  whiptail --msgbox "You will now be asked to enter a new password for the root user" 20 60 1
+  whiptail --msgbox "You will now be asked to enter a new password for the *root* user" 20 60 1
   passwd root &&
   whiptail --msgbox "Password changed successfully" 20 60 1
 }
@@ -587,7 +633,7 @@ do_lcd_login() {
     if ! grep -q "^t.*:.*:respawn:.*tty1" /etc/inittab; then
       printf "tty1::respawn:/sbin/getty 38400 tty1\n" >> /etc/inittab
     fi
-    whiptail --msgbox "LCD virtual console is now enabled" 20 60 1
+    whiptail --msgbox "LCD virtual console will now be enabled at next reboot" 20 60 1
   else
     return $RET
   fi
@@ -774,7 +820,8 @@ do_audio() {
 }
 
 do_rtc_ntp() {
-  whiptail --yesno "Updating APF Real Time Clock using NTP. Require internet connection (may take time to synchronize) and battery on RTC." 20 60 2
+  DATE=`date`
+  whiptail --yesno "Updating system's Real Time Clock using NTP. Require internet connection (may take time to synchronize) and battery on RTC. Actual one is: $DATE" 20 60 2
   if [ $? -eq 0 ]; then
     udhcpc -i eth0 &&
     ntpd -nqp 217.147.208.1 &&
@@ -933,7 +980,7 @@ if [ -n "${OPT_MEMORY_SPLIT:-}" ]; then
 fi
 
 do_internationalisation_menu() {
-  FUN=$(whiptail --title "APF6 Software Configuration Tool (apf-config)" --menu "Internationalisation Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Back --ok-button Select \
+  FUN=$(whiptail --title "Armadeus SOM Software Configuration Tool (apf-config)" --menu "Internationalisation Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Back --ok-button Select \
     "I1 Change Locale" "Set up language and regional settings to match your location" \
     "I2 Change Timezone" "Set up timezone to match your location" \
     "I3 Change Keyboard Layout" "Set the keyboard layout to match your keyboard" \
@@ -952,13 +999,13 @@ do_internationalisation_menu() {
 }
 
 do_advanced_menu() {
-  FUN=$(whiptail --title "APF6 Software Configuration Tool (apf-config)" --menu "Advanced Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Back --ok-button Select \
-    "A1 Hostname" "Set the visible name for this APF on a network" \
+  FUN=$(whiptail --title "Armadeus SOM Software Configuration Tool (apf-config)" --menu "Advanced Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Back --ok-button Select \
+    "A1 Hostname" "Set the visible name for this system on a network" \
     "A2 SSH" "Enable/Disable remote command line access to your APF using SSH" \
     "A3 Serial" "Enable/Disable serial console" \
     "A4 LCD login" "Enable/Disable login on the LCD/HDMI" \
     "A5 LCD timeout" "Set framebuffer sleep mode timeout" \
-    "A6 RTC/NTP" "Update APF clock through NTP" \
+    "A6 RTC/NTP" "Update system's clock through NTP" \
     "A0 Update" "Update this tool to the latest version (Debian only)" \
     3>&1 1>&2 2>&3)
   RET=$?
@@ -978,8 +1025,8 @@ do_advanced_menu() {
   fi
 }
 
-do_failsafe_menu() {
-  FUN=$(whiptail --title "APF6 Software Configuration Tool (apf-config)" --menu "Failsafe actions" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Back --ok-button Select \
+do_recovery_menu() {
+  FUN=$(whiptail --title "Armadeus SOM Software Configuration Tool (apf-config)" --menu "Recovery actions" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Back --ok-button Select \
     "F1 Check eMMC" "Check for errors in ext4 filesystems" \
     "F2 Format eMMC" "Needed after a recover" \
     "F3 Fill eMMC with zeroes" "To have a brand new clean eMMC" \
@@ -989,26 +1036,42 @@ do_failsafe_menu() {
     return 0
   elif [ $RET -eq 0 ]; then
     case "$FUN" in
-      F1\ *) do_check_emmc ;;
-      F2\ *) do_format_emmc ;;
-      F3\ *) do_clear_emmc ;;
+      F1\ *) do_check_emmc $1 ;;
+      F2\ *) do_format_emmc $1 ;;
+      F3\ *) do_clear_emmc $1 ;;
       *) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
     esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
   fi
 }
 
+board=`cat /etc/machine`
+check_board()
+{
+  if [ "$board" != "APF6" ] && [ "$board" != "OPOS6UL" ]; then
+    whiptail --msgbox "This SOM ($board) is not supported by this tool !" 20 60 1
+    exit 1
+  fi
+}
 
-# Interactive use loop
 #
+# Interactive use/main loop
+#
+check_board
+if [ "$board" == "APF6" ]; then
+  MMC_DEV=mmcblk2
+fi
+if [ "$board" == "OPOS6UL" ]; then
+  MMC_DEV=mmcblk0
+fi
 calc_wt_size
 while true; do
-  FUN=$(whiptail --title "APF6 Software Configuration Tool (apf-config)" --menu "Setup Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Finish --ok-button Select \
+  FUN=$(whiptail --title "Armadeus SOM Software Configuration Tool (apf-config)" --menu "Setup Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Finish --ok-button Select \
     "1 Expand Filesystem(s)" "OS can then use all eMMC/SD space" \
     "2 Change User Password" "Change default user password" \
     "3 Enable Boot to Desktop" "(Debian only)" \
     "4 Internationalisation Options" "Set up language/regional settings" \
     "5 Advanced Options" "Configure advanced settings" \
-    "6 Failsafe" "Actions when in failsafe mode (only !)" \
+    "6 Recovery" "Actions when in recovery mode (only !)" \
     "9 About apf-config" "Informations about this tool" \
     3>&1 1>&2 2>&3)
   RET=$?
@@ -1016,12 +1079,12 @@ while true; do
     do_finish
   elif [ $RET -eq 0 ]; then
     case "$FUN" in
-      1\ *) do_expand_rootfs ;;
+      1\ *) do_expand_rootfs $board ;;
       2\ *) do_change_pass ;;
       3\ *) do_boot_behaviour ;;
       4\ *) do_internationalisation_menu ;;
       5\ *) do_advanced_menu ;;
-      6\ *) do_failsafe_menu ;;
+      6\ *) do_recovery_menu $MMC_DEV ;;
       9\ *) do_about ;;
       *) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
     esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
